<?php

namespace Aramx\Shipping\Console\Command;
use Symfony\Component\Console\Input\InputOption;

class MyCustomCommand extends \Symfony\Component\Console\Command\Command
{
    private const NAME = 'OrderId';
    private $_orderHelper;

    protected function configure()
    {
        $this->setName('Send:Aramex');
        $this->setDescription('To send the order details to Aramex');
        $this->addOption(
            self::NAME,
            null,
            InputOption::VALUE_REQUIRED,
            'Name'
        );
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function __construct(\Aramx\Shipping\Helper\OrderData $orderHelper)
    {
        $this->_orderHelper = $orderHelper;
        parent::__construct();
    }

    public function execute(\Symfony\Component\Console\Input\InputInterface $input, \Symfony\Component\Console\Output\OutputInterface $output)
    {
        // get orderid
        $orderId = $input->getOption(self::NAME);
        // retrieve the order details using orderid
        \Magento\Framework\App\ObjectManager::getInstance()->get('Psr\Log\LoggerInterface')->debug('i am here -->'.$orderId);
        $orderdetails = $this->_orderHelper->getOrderInfo1($orderId);
        $customerAddress=$orderdetails->getData('customer_address');
        $request =[
            "customerName"=>$orderdetails['customer_name'],
            "aramex_id"=> $orderdetails['entity_id']
        ];
        $req=json_encode($request);//convert array to json
        //send req to aramex url , using curl
        $curl = curl_init('http://localhost:8023/json.php?key=1');
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_POST,true);
        curl_setopt($curl, CURLOPT_POSTFIELDS, $req);
        $response=curl_exec ($curl);
        curl_close ($curl);
        // echo $response;
        //php curl post
        \Magento\Framework\App\ObjectManager::getInstance()->get('Psr\Log\LoggerInterface')->debug('i am customer_id -->'. $orderdetails->getData('protect_code'),);
        // send the order details to Aramex
        $output->writeln('Order details has been sent to Aramex'.$orderId);
        // using curl call the Aramex API and send the data
        // read the response if successfull, exit
        // if error, log
    }


}
